# Use official Node.js image
FROM node:20

# Set working directory
WORKDIR /root/apps/connect360

# Set environment to production
ENV NODE_ENV=production

# Copy package files and install dependencies
COPY package.json yarn.lock ./
RUN yarn install --production

# Copy the rest of the application
COPY . .

# Expose the port
EXPOSE 3000

# Start the app
CMD ["node", "dist/index.js"]



