name: Build and Deploy - Connect 360 Server

on:
  release:
    types: [published]

jobs:
  build:
    #if: startsWith(github.event.release.tag_name, 'connect360-server-')
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install
        working-directory: ./server

      - name: Build project
        run: yarn build
        working-directory: ./server

      - name: Verify connect360-server dist folder
        run: ls server/dist

      - name: Deploy files using SCP
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PORT: ${{ secrets.SSH_PORT || '22' }}
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/private_key
          chmod 600 /tmp/private_key

          scp -o StrictHostKeyChecking=no -i /tmp/private_key -P $SSH_PORT -r server/dist/ $SSH_USER@$SSH_HOST:apps/connect360

          ssh -o StrictHostKeyChecking=no -i /tmp/private_key -p $SSH_PORT $SSH_USER@$SSH_HOST << 'EOF'
            echo "You can run post-deploy commands here"
          EOF

          rm /tmp/private_key
